### ISSUE TITLE
Help with modification for python 3.6

### ISSUE THREAD

**Issue by kyp0717** [travisbrown/haskell-cpython#2]
Hi Travis,
I was wondering if you can help me make the modifications to your lib so that it will work with python 3.6.

Thanks,
Ky

**Comment by travisbrown** [comment]
@kyp0717 Sorry, but the goal of this fork was supporting Python 2; for Python 3 you should talk to the maintainers of the original [haskell-cpython](http://hackage.haskell.org/package/cpython).
